<?php

return array(
	'mtcms' => array(
        'main' => array(
			'logo' => 'mtheme/image/logo.png', 
			'ico' => 'mtheme/image/favicon.png', 
			'load' => 'mtheme/image/loading.gif', 
			'footertips' => '<p>本站只提供WEB页面服务，本站不存储、不制作任何视频，不承担任何由于内容的合法性及健康性所引起的争议和法律责任。</p>
<p>若本站收录内容侵犯了您的权益，请附说明联系邮箱，本站将第一时间处理。</p>',
            'detailurl' => '0',
             'searchwd' => 'MT主题',
             'searchtipsbtn' => '1',
             'searchtips' => '请输入搜索关键词！',
             'searchhot' => '1',
             'hotsearch' => '1',
             'footerone' => '1',
             'footeroneurl' => 'https://www.cmszyb.com/',
             'footeronetxt' => 'Telegram群',
             'oneblank' => '1',
             'footertwo' => '1',
             'footertwourl' => '/index.php/gbook/index.html',
             'footertwotxt' => '问题反馈',
             'twoblank' => '1',
              'footerthree' => '1',
             'footerthreeurl' => '/index.php/rss/baidu.xml',
             'footerthreetxt' => '网站地图',
             'threeblank' => '1',
              'ftdiy1' => '0',
             'ftdiy1url' => '',
             'ftdiy1txt' => '',
             'ftdiy1blank' => '0',
              'ftdiy2' => '0',
             'ftdiy2url' => '',
             'ftdiy2txt' => '',
             'ftdiy2blank' => '0',
             'footertj' => '1',
             'filter' => '0'
			),
			'menu' => array(
			'leftmenuid' => '1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,25,26,27,28', 
			'leftblank' => '0', 
			'rmenutopic' => '1', 
			'rmenutopictxt' => '专题', 
			'rmenutopicico' => 'xe779', 
			'rmenutopicurl' => '/index.php/topic/index.html', 
			'rmenutopicblank' => '0', 
			'rmenuapp' => '1', 
			'rmenuapptxt' => 'APP', 
			'rmenuappico' => 'xe654', 
			'rmenuappurl' => '/index.php/label/app.html', 
			'rmenuappblank' => '0', 
			'rmenuuser' => '0', 
			'rmenudiy1' => '0', 
			'rmenudiy1txt' => '', 
			'rmenudiy1ico' => '', 
			'rmenudiy1url' => '', 
			'rmenudiy1blank' => '0', 
			'rmenudiy2' => '0', 
			'rmenudiy2txt' => '', 
			'rmenudiy2ico' => '', 
			'rmenudiy2url' => '', 
			'rmenudiy2blank' => '0', 
			'zongkg' => '1', 
			'up' => '1', 
			'gbook' => '1',
			'reload' => '1',
			'rxdiy' => '0', 
			'rxdiytxt' => '', 
			'rxdiyico' => '', 
			'rxdiyurl' => '', 
			'rxdiyblank' => '0'
			)
			,
			'home' => array(
			'slidebtn' => '1', 
			'slidelevel' => '9', 
			'slideby' => 'time', 
			'slideorder' => 'desc',
			'slidesub1' => 'vod_blurb',
            'slidesub2' => 'vod_remarks',
            'slidetxt' => '播放正片',
             'slideico' => 'xe905',
             'indexhot' => '1',
             'indexhottxt' => '重磅热播',
             'indexhotid' => '1,2,3,4',
              'indexhotlevel' => '1',
              'indexhotnum' => '6',
              'indexrtips' => 'vod_class',
              'indexftips' => 'vod_actor',
              'indexhsub1' => 'vod_actor',
             'indexhsub2' => 'vod_blurb',
             'indexhsubbtn' => '1',
             'indexhsubbtntxt' => '看',
             'indexhsubbtnico' => 'xe94f',
             'indextypeid' => '1,2,3,4',
               'indextype' => '1', 
             'indextypeidbtn' => '1',
             'indextypenum' => '8',
            'indextypetips1' => 'vod_score',
            'indextypetips2' => 'vod_class',
            'indextypeorder' => 'desc',
            'indextypeby' => 'time',
            'indextypeyear' => '2023',
            'indextypexftips' => 'vod_actor',
            'indextopic' => '1',
            'indextopictxt' => '精彩专题',
            'indextopicnum' => '5',
             'indexlink' => '1',
            'indexlinktxt' => '友情链接',
            'indexlinknum' => '30'
			),
			'yemian' => array(
			  'liketxt' => '相关影片',
			  'likenum' => '16',
			  'likeby' => 'time',
			  'likeorder' => 'desc',
			  'likeyear' => '2023',
			  'diyqrcode' => '0',
			  'diyqrcodeimg' => '',
			  'diyqrcodetxt' => '手机扫一扫观看影片',
			  'deplaylist' => '1',
			  'delike' => '1',
			  'decontent' => '1',
			  'deshare' => '1',
			  'decomment' => '1',
			  'playtips' => '1',
			  'playtipstxt' => '<li><i class="ol1">提示</i>不要轻易相信视频中的广告，谨防上当受骗!</li>
<li><i class="ol3">提示</i>如果无法播放请重新刷新页面，或者切换线路。</li>
<li><i class="ol7">提示</i>视频载入速度跟网速有关，请耐心等待几秒钟。</li>',
			  'copyright' => '应版权方要求该资源已下架',
			  'plreport' => '1',
			  'plcomment' => '1',
			  'plshare' => '1',
			  'pllike' => '1',
			  'pldiy' => '0',
			  'pldiytxt' => '',
			  'pldiyico' => '',
			  'pldiyblank' => '',
			  'pldiyurl' => '',
			  'typeid' => '1',
			  'typeupdate' => '1',
			  'typeupdatenum' => '16',
              'typeupdateyear' => '2023',
              'typemore' => '1',
              'id' => '1,2',
              'areaid' => '3,4',
              'classid' => '',
              'typeyear' => '',
              'typenum' => '16',
              'typeby' => 'time',
              'typeorder' => 'desc',
              	'filter' =>
                array (
                    'id-1' =>
                        array (
                            0 => 'a',
                            1 => 'b',
                            2 => 'c',
                            3 => 'd',
                            4 => 'e',
                        ),
                    'id-2' =>
                        array (
                            0 => 'a',
                            1 => 'b',
                            2 => 'c',
                            3 => 'd',
                            4 => 'e',
                        ),
                    'id-3' =>
                        array (
                            0 => 'a',
                            1 => 'b',
                            2 => 'c',
                            3 => 'd',
                            4 => 'e',
                        ),
                    'id-4' =>
                        array (
                            0 => 'a',
                            1 => 'b',
                            2 => 'c',
                            3 => 'd',
                            4 => 'e',
                        ),
                    'id-' => '',
                ),
            'showyear' => '',
              'shownum' => '56',
              'showby' => 'time',
              'showorder' => 'desc',
                'searchnum' => '10',
              'searchby' => 'time',
              'searchorder' => 'desc',
              'searchde' => '1',
               'searchrtxt' => '热播影片',
			  'searchrnum' => '15',
			  'searchrby' => 'time',
			  'searchrorder' => 'desc',
			  'searchryear' => '',
              'searchhz' => 'vod_hits',
              'searchrlevel' => 'all',
              'topictxt' => '精彩专题',
			  'topicnum' => '30',
			  'topicby' => 'time',
			  'topicorder' => 'desc',
              'ranktxt' => '热映排行',
              'ranksub' => '新鲜热播好剧',
              'rankid' => '1,2,3,4,6,7,8,9,10,11,12,13,14,15,16',
              'rankby' => 'time',
              'rankorder' => 'desc',
              'ranknum' => '10',
              'rankyear' => '',
              'rankhz' => 'vod_hits',
              'apptxt' => 'MT主题 网站APP', 
			'appentxt' => '海量高清影片、更佳观影体验，尽在MT APP', 
			'android' => '1', 
			'ios' => '1', 
			'win' => '1', 
			'androidurl' => '', 
			'iosurl' => '', 
			'winurl' => '', 
			'androidicon' => 'xe960', 
			'iosicon' => 'xe959', 
			'winicon' => 'xe961', 
			'androidtxt' => 'Android版', 
			'iostxt' => 'ios版', 
			'wintxt' => '客户端版', 
			'appqrcodeimg' => 'mtheme/image/qrcode.png',
              'appqrcodetxt' => '扫一扫下载APP www.cmszyb.com'
			),
			'qita' => array(
// 			'notice' => '1', 
// 			'noticetxt' => '网站公告', 
// 			'noticecontent' => '<p>欢迎使用MT主题</p>    
// <p>MT是一款多功能苹果CMSv10暗黑大气主题</p>
// <p>官方网站：<span style="color:#59Ceff">www.cmszyb.com</span></p>
// <p>苹果cms模板大全：<span style="color:#59Ceff">www.mtheme.cc</span></p>
// <p>苹果cms论坛：<span style="color:#59Ceff">www.mbbsm.com</span></p>
// <P style="text-align: center;"><a href="https://www.cmszyb.com/" target="_blank">点我进入官网</a></p>
//  <p>点击我已了解，弹窗当天不在弹出！</p>', 
//             'gbook' => '1', 
// 			'gbooktxt' => '官方提示：请不要轻易相信留言板中的广告以及链接，以免被骗！！！ '
			)
			, 
		'ads' => array(
			'index' => '0', 
			'indexcode' => '', 
			'indexlist' => '0', 
			'indexlistcode' => '', 
			'detailcode' => '', 
			'detail' => '0', 
			'playcode' => '', 
			'play' => '0', 
			'footcode' => '', 
			'foot' => '0'
		)
			
	)
);